name="ScreenZ";
tooltip="ScreenZ";
overview="Customized main menu with music and loading screen images with mask used on The Old Republic server.";
picture="ScreenZ\data\picture.paa";
logoSmall="ScreenZ\data\logoSmall.paa";
logo="ScreenZ\data\logo.paa";
logoOver="ScreenZ\data\logo.paa";
action="https://steamcommunity.com/sharedfiles/filedetails/?id=3643948795";
author="moldypenguins";
version="1.3";
